### ISSUE TITLE
[2.1a] Cooking plate with chicken

### ISSUE THREAD

**Issue by Belgabor** [defeatedcrow/AppleMilkTea2_1.7.10#28]
I'm not sure whether I'm missing something, but currently chicken doesn't seem to work on the new iron cooking plate. Beef, pork and clams all work, but chicken doesn't. I can put it on the plate, but it doesn't rotate and also never cooks.

**Comment by defeatedcrow** [comment]
![oven](https://dl-web.dropbox.com/s/nuq1ithknfxgg59/ovenmode.png)

Description of the new specification is missing, I'm sorry.

New cooking griddle will require a "oven mode" for cooking the chicken.

Oven mode requires placing the stone material block that upper and any of the side 3 direction of iron plate. (Example of image.)
Stone material blocks in the upward direction may have some distance away from the steel plate.

The "oven mode" is ready for adding some cooking recipe (eg, bread or pizza) that future requires oven or kiln.
Roast chicken changed to oven-mode recipe, for providing to the MOD user an opportunity to actually try out new mode.

**Comment by Belgabor** [comment]
Nice! May I suggest to add some help messages in chat? So if you put chicken (or some other "oven mode" ingredient) on a "simple" plate it says something like "Incomplete oven structure, <ingredient> can only be cooked in oven mode".

**Comment by defeatedcrow** [comment]
I thank to your good idea!

I just have to seek a clear discrimination method of oven mode, your a good idea became my help.
In the next update, I will implement a chat message on the right-click operation.

**Comment by Belgabor** [comment]
Awesome!
One small thing, could you make an exception for Forge Microblocks? I think they do not count as solid blocks, but I think accepting them may allow for more elaborate designs.
![2015-01-29_04 52 57](https://cloud.githubusercontent.com/assets/36589/5952258/7d8a318e-a773-11e4-8f57-2dd1dd5da4bd.png)

**Comment by defeatedcrow** [comment]
Sorry, "Forge Microblocks" is What MOD?
Is what I know, one thing is the ForgeMultipart API by Chicken-Bone, and the other is a microblocks by Immibis. Might others also.

In either case, it is necessary to my modding learning.
Therefore I will consider as a long-term challenge.

Alternatively, it is that the current oven mode to stop to request a "stone material block", and it allows the construction of the oven by using the block any non-air.
I think that it can be more quickly resolved in this way.

**Comment by Belgabor** [comment]
I mixed it up again, I can never remember what is the name of the actual mod and what is the name of the block =) Yes, I was referring to Forge Multipart.
Just checking for non-air is probably a good short-term solution.

**Comment by defeatedcrow** [comment]
At Version2.2a, simplified iron oven mode conditions and chat messages to inform the cooking failure has been added.
Perhaps, I think the problem was solved.

**Comment by Belgabor** [comment]
Great! There seems to be a small bug though. If the top block isn't a solid one it doesn't work in a strange way. I can put chicken on the plate, but it doesn't cook. I get no message and I also cannot get the chicken off the plate without breaking it.

**Comment by defeatedcrow** [comment]
Oven mode requires "the sun is not visible conditions" on the top surface. This is an internal process utilizes a flag called World.canBlockSeeTheSky (x, y, z).

Thus, the iron plate will oven mode if there is opaque block in the sky that is away from the iron plate. It is, for example, is the case if you put the iron plate in a building with a roof.

**Comment by Belgabor** [comment]
Ah ok, I understand.
Could you add that to the message and show it under these conditions? Also the fact that I need to break the plate to get the chicken back (right click with an empty hand does not work under these conditions) seems like a bug =)

**Comment by defeatedcrow** [comment]
At update 2.2c, iron plate also changes to the oven mode when there is a transparent block on.
Since the past specifications seemed inconvenient, I have changed the oven mode conditions.
Perhaps oven mode, I think that it became easier to use than ever before. Thank you!

**Comment by Belgabor** [comment]
Great! But it seems like there is still something wrong, now chicken seems to work without oven mode. (There is no block above the plate in this instance).
![2015-02-05_04 53 20](https://cloud.githubusercontent.com/assets/36589/6054819/f4a1d9fa-acf2-11e4-87bf-9efe4dfb1465.png)

**Comment by Belgabor** [comment]
One more thing I noticed, you can put valid items on the plate with a hopper, not sure if that is intended. The main issue is, if you do that, the item doesn't cook. It turns for a while and then stops without turning into the cooked form.

**Comment by defeatedcrow** [comment]
At 2.3a, I guess it's running correctly.

**Comment by Belgabor** [comment]
Yes, seems to work fine now, thanks!
