### ISSUE TITLE
[Suggestion] Evaporator: Button to destroy contained liquid

### ISSUE THREAD

**Issue by Belgabor** [defeatedcrow/AppleMilkTea2_1.7.10#32]
When processing items in the evaporator you can end up with amounts of liquid that you cannot get out with a bucket or bottle. It would be nice to have a GUI button to destroy the liquid in the evaporator so you don't have to break and replace it to get it out.

**Comment by defeatedcrow** [comment]
Please put a sand block on liquid container area of the evaporator GUI. From 2.3a, thereby liquid tank is empty.

**Comment by Belgabor** [comment]
I read that in the changelog, I love the idea!

**Comment by Belgabor** [comment]
I consider this solved, so I'll close the issue.
