### ISSUE TITLE
Ore doubling off config

### ISSUE THREAD

**Issue by Mrbysco** [defeatedcrow/AppleMilkTea2_1.7.10#34]
I would love to be able to disable the jaw crushers ore doubling... maybe a config option.

**Comment by Belgabor** [comment]
I am working on a MineTweaker addon for Apple, Milk and Tea that allows you to customize recipes, would that be enough for your purposes?

**Comment by Mrbysco** [comment]
Yes Pretty much Belgabor.. Would I be able to use it in my modpack then? (Magic Maiden)

**Comment by Belgabor** [comment]
Sure, it's MIT licensed. You can find it here: https://github.com/Belgabor/AMTweaker
Just be aware that I didn't get much testing done, but it should mostly work fine as long as you only use the any-metadata (:*) operator where I noted it is safe.

**Comment by Belgabor** [comment]
Hm, there might be an issue, probably wait till I release a fix.

**Comment by defeatedcrow** [comment]
The way of delete or modified individual recipes can only be by the API.
Safe operation of the config changing system is difficult for me. 
The config can be changed by all mod user. It would be undesirable for me.

And, if I may add, It's the config for collectively change "the number of jaw crusher product the ore powder". If you allow, I consider in 1-3 pieces (including by-product).
