### ISSUE TITLE
[2.4a] Issues with PotionExtention

### ISSUE THREAD

**Issue by Belgabor** [defeatedcrow/AppleMilkTea2_1.7.10#39]
There seems to be an issue with Potion Extension in the new version. It didn't update to 1.0.4 automatically. Even when forced to (by deleting the old version) it doesn't recognize it is there (message "Required Core mod not loaded" when you load a save).

**Comment by defeatedcrow** [comment]
Oh, Sorry! Thanks to your report.

In the current version, version notation of PotionExtension has been changed. AMT2 has a version determination system (Auto), but, it does not recognize the time series of versions correctly.
Unfortunately, Japan informal forum is down by DoS attacks. Therefore, it is not possible to manually introduce the latest PotionExtension.
I'm going to do an update of 2.4b in a hurry.

**Comment by Belgabor** [comment]
Thanks =)

**Comment by defeatedcrow** [comment]
I'm sorry, in next version 2.4b, automatic deletion function is not resolved.
In 2.4b, will occur forced crash with old premised mod. mod user must manually delete the old PotionExtension. Then, automatic download function will start normally.

It seems that the automatic delete function of the premise MOD does not work properly. However, I was not able to correctly fix the DepLoader.
Forced crash is extreme way, but, I guess it is reliable way than tell the "Request for update" in the message at the time of login...
