### ISSUE TITLE
[Suggestion] API for covering in chocolate

### ISSUE THREAD

**Issue by Belgabor** [defeatedcrow/AppleMilkTea2_1.7.10#40]
I've had a feature request for a custom chocolate covering recipe (Belgabor/AMTweaker#1). I think it would be a nice addition to the feature set of the API if you have the time to implement it. If possible, don't restrict it to the items AMT provides, so both output and input item can be chosen freely.

**Comment by defeatedcrow** [comment]
I guess it's good idea.
So I'll make the API, probably it will be like the other recipe API.

**Comment by defeatedcrow** [comment]
At 2.4c, I added the API and the recipe browsing handler for the NEI and CG.

**Comment by Belgabor** [comment]
Awesome, implemented in v0.4 of AMTweaker.
