### ISSUE TITLE
Grater not working when grater took damage

### ISSUE THREAD

**Issue by Mrbysco** [defeatedcrow/AppleMilkTea2_1.7.10#43]
I maintain a modpack called Magic maiden.
One of the people on my server reported to me that the grater recipes are not working.
It works on a newly made grater. But only works 1 time.
After it takes damage its not working anymore
Undamaged:
![Image of undamaged](http://i.imgur.com/P9iVtMv.png)
Damaged:
![Image of undamaged](http://i.imgur.com/nJRv22b.png)

**Comment by defeatedcrow** [comment]
I thank your report!
This problem was fixed at 2.4e.
