### ISSUE TITLE
[2.7b] Crash with VillagerRegistry :(

### ISSUE THREAD

**Issue by TheSlimeMan** [defeatedcrow/AppleMilkTea2_1.7.10#49]
yes... I tried to run my modpack and this happens.. Do you know how I can fix?
---------------------------------------
http://pastebin.com/cvdU9YF8

**Comment by defeatedcrow** [comment]
It is a crash that happened by duplication of villagers ID.
Please change the villagers of ID in the config file of AppleMilkTea2. (DCsAppleMilk.cfg) The default number is 15.

**Comment by TheSlimeMan** [comment]
thank you so much!
