### ISSUE TITLE
Corrupted shapeless ore recipe

### ISSUE THREAD

**Issue by Adaptivity** [defeatedcrow/AppleMilkTea2_1.7.10#51]
Hardcore Ender Expansion said that I should report this to you. Also, pinging @chylex 
Log: http://pastebin.com/V1r1THTL
Versions:
HEE: 1.8.2 
AppleMilkTea2: V2.7h.
Forge: 1481

**Comment by defeatedcrow** [comment]
Thanks to your report. I'll fix it in next update.

**Comment by Adaptivity** [comment]
Thanks for the fix!
