### ISSUE TITLE
Placed bottles have missing localization

### ISSUE THREAD

**Issue by Adaptivity** [defeatedcrow/AppleMilkTea2_1.7.10#54]
Gin, Wine, Beer and other bottles (which are placed in world) have no localization.

**Comment by Adaptivity** [comment]
@defeatedcrow I mean not just empty bottles.

**Comment by defeatedcrow** [comment]
The block state bottles is different from the item state bottles.
All bottles has same unlocalised name, when these are block state. And these properties (like type or direction) is held in TileEntity.
