### ISSUE TITLE
Cooking Iron Plate complains about not having heat source

### ISSUE THREAD

**Issue by eslachance** [defeatedcrow/AppleMilkTea2_1.7.10#55]
When the plate is on top of a lava block, right-clicking on it with zombie flesh will very often give the message indicating that it requires a heat source under it. This does not happen when right-clicking with an empty hand. The plate works anyways (and converts zombie flesh to leather, yay!), however.

**Comment by eslachance** [comment]
Additional Information: I was playing this in the Horizons: Daybreaker mod pack.

**Comment by defeatedcrow** [comment]
Thanks to your report!
That will be fixed at next update (2.8a).

**Comment by eslachance** [comment]
I assume this was closed at one point in the last 2 years! :D
