### ISSUE TITLE
start up crash - my own modpack 

### ISSUE THREAD

**Issue by AeroyrHwrdd** [defeatedcrow/AppleMilkTea2_1.7.10#65]
Here is the crash report: 

https://gist.github.com/AeroyrHwrdd/d1a6ea25ab63a4731639

It appears to only happen when I add Apple, Milk & Tea.

Are there any mods this is not compatible with.

**Comment by defeatedcrow** [comment]
This is just a duplicate of the villager ID.
Numeric ID may require the user to avoid duplication. They are not a bug that should be corrected by me. Look at the config file (DCsAppleMilk.cfg).

Cafe clerk: ID specified in the configuration
Warehouse administrator: The following ID of cafe clerk

**Comment by AeroyrHwrdd** [comment]
Cheers, I have changed the ID on config. Works fine now. So glad as I get to play with your mod.
