### ISSUE TITLE
Nei compatibility 1.7.10

### ISSUE THREAD

**Issue by 31trainman** [defeatedcrow/AppleMilkTea2_1.7.10#66]
Some items/ blocks are registered during the preint phase leading to not being able to see the recipe in nei via the r key.  http://pastebin.com/UHGcWZxH Amt2 version 2.9k mod list:  http://pastebin.com/ss7RbZ2k forge 1614 mc 1.7.10 Java 8 update 91 Mac OS X 10.11.4

**Comment by defeatedcrow** [comment]
It's NOT a confliction with NEI. It DID NOT be caused by AMT2.
You guessed wrong cause.

Why don't you read my response in the previous issue?
https://github.com/defeatedcrow/AppleMilkTea_1.7.X/issues/1

OK, I'll NEVER support the play environments including Dragon API.
THAT'S ALL.
