### ISSUE TITLE
dust charcoal is in dust coal ore dictionary

### ISSUE THREAD

**Issue by 5lx** [defeatedcrow/AppleMilkTea2_1.7.10#67]
in /java/mods/defeatedcrow/handler/RegisterOreHandler.java

``` java
OreDictionary.registerOre("dustCharcoal", new ItemStack(DCsAppleMilk.dustWood, 1, 1));
OreDictionary.registerOre("dustCoal", new ItemStack(DCsAppleMilk.dustWood, 1, 1));
```

If I use Gregtech mod with this mod, dustCharcoal will auto change to dustCoal

**Comment by defeatedcrow** [comment]
Your purpose is not written. You are asking what to me?

Phenomenon that is happening is the specifications, they are not a bug. 
(Also, I do not have the right to change the specification of Greg. Of course, this mod made for me, not made for gregtech support.)

Please write what you are asking to me. It does not look to the needs or questions.

**Comment by 5lx** [comment]
Sorry about my unclear description. I sent this issue very hurry this morning. The things is, many mods differently treat charcoal dust and coal dust. For example, you can't use Charcoal dust to make industrial diamond in IC2. The code make Apple&Milk&Tea 2 charcoal dust belongs to ore:dustCoal and ore:dustCharcoal, So I thought this might be a small bug, and submitted the issue.

I really like your mod. Foods and drinks look so good. And I hope this mod becomes better. But just as you said, this mod is made for yourself, not made for supporting other mods. So it is a kind suggestion that separate charcoal dust and coal dust or add a config to control whether add charcoal dust into dustCoal ore dictionary. If you don't like that, please feel free to ignore it.

**Comment by defeatedcrow** [comment]
Thank you to description.
Your request seems can be solved by using MineTwaker, simply by removing the charcoal dust from "dustCoal" dictionary name. I would recommend it to you.

I have assumed compatibility with IC2 coal powder. One of the design concept is the development of agriculture and forestry. So, I did so in order to take advantage of the Vegetable carbon source.

**Comment by 5lx** [comment]
Thank you for your suggestion, and I'll try it later.
